# pvc
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: ebs-dynamic
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: roboshop-ebs
  #volumeName: ebs-dynamic not required for dynamic
  resources:
    requests:
      storage: 2Gi
---
# pod
apiVersion: v1
kind: Pod

metadata: 
  name: nginx
  labels:
    purpose: ebs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-vol
      mountPath: /usr/share/nginx/html
  # nodeSelector:                                # not require for dynamic
  #   topology.kubernetes.io/zone: us-east-1b
  volumes:
  - name: nginx-vol
    persistentVolumeClaim:
      claimName: ebs-dynamic

---
# lb
apiVersion: v1
kind: Service

metadata:
  name: nginx-ebs-dynamic
  
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007






