kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-080bc47fa1a9e3e1f
  directoryPerms: "700"
  basePath: "/roboshop" # optional
  