apiVersion: v1
kind: Pod

metadata:
  name: nginx
  namespace: roboshop 
  labels:
    project: roboshop
    env: dev

spec:
  containers:
  - name: nginx
    image: nginx 
    ports:
    - containerPort: 80