apiVersion: v1
kind: Pod

metadata: 
  name: error-test
  label:
    purpose: to see errors

spec:
  containers:
  # - name: frontend
  #   image: nginxsdd

  - name: almalinux
    image: almalinux:9
