apiVersion: v1
kind: Pod

metadata:
  name: env-demo
  labels:
    purpose: environemnt variables

spec:
  containers:
  - name: nginx
    image: nginx
    env: 
    - name: course
      value: devops
    - name: trainer
      value: sivakumar
    - name: batchname
      value: daws86s