apiVersion: v1
kind: Pod

metadata:
  name: service-demo
  # These labels are used to register this pod with service
  labels:
    project: roboshop
    component: frontend
    environemnet: dev

spec:
  containers:
  - name: nginx
    image: nginx
