apiVersion: v1
kind: Pod

metadata:
  name: service-lb-demo
  labels:
    project: roboshop
    environment: dev
    component: frontend
    purpose: load-balancer

spec:
  containers:
    - name: nginx
      image: nginx
