apiVersion: apps/v1
kind: Deployment

metadata: 
  name: nginx
  labels:
    project: roboshop
    purpose: deployment-demo

spec:
  replicas: 4
  selector:
    matchLabels:
      project: roboshop
      purpose: deployment-demo

  template:
    metadata:
      labels:
        project: roboshop
        purpose: deployment-demo

    spec:
      containers:
      - name: nginx
        iamge: nginx:latest

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   type: LoadBalancer
#   selector:
#     purpose: headless-svc-demo
#     project: roboshop
#   ports:
#     - protocol: TCP
#       port: 80 # service port
#       targetPort: 80 # container port
  