apiVersion: apps/v1
kind: Deployment

metadata: 
  name: nginx
  labels:
    project: roboshop
    purpose: deployment-demo

spec:
  replicas: 4
  selectors:
    matchLabels:
      project: roboshop
      purpose: deployment-demo

  template:
    metadata:
      labels:
        project: roboshop
        purpose: deployment-demo

    spec:
      containers:
      -  name: nginx
         iamge: nginx:latest
  